all: p1 p2 p3 p4
p1: addition.c
	gcc addition.c -o addition
	./addition

p2: substraction.c
	gcc substraction.c -o substraction
	./substraction

p3: multiplication.c
	gcc multiplication.c -o multiplication
	./multiplication

p4: division.c
	gcc division.c -o division
	./division

